# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1

        environment:
          AWS_REGION: eu-west-1
          AWS_DEFAULT_REGION: eu-west-1
          AWS_SSH_USERNAME: ubuntu
          AWS_SOURCE_AMI: ami-add175d4
          AWS_INTANCE_TYPE: c4.large
          KUBERNETES_VERSION: 1.9.5
          KUBERNETES_RELEASE_TAG: v1.9.5
          ETCD_RELEASE_TAG: 3.1.11
          K8S_DNS_RELEASE_TAG: 1.14.8
          SPARK_RELEASE_TAG: v2.2.1-k8s-1.0.11
          ZEPPELIN_RELEASE_TAG: v0.9.0-k8s-1.0.12
          HELM_RELEASE_TAG: v2.8.2
          WEAVE_RELEASE_TAG: 2.2.1
          PROMETHEUS_RELEASE_TAG: v2.1.0
          PUSHGATEWAY_RELEASE_TAG: v0.4.0-banzaicloud-0.1.1
          TRAEFIK_RELEASE_TAG: 1.5.3
          BASE_NAME: pipeline-cluster-image
    steps:
      - checkout

      - run:
          name: Build Packer
          no_output_timeout: 1800
          command: |
            GIT_REV=$(git rev-parse --short HEAD)
            GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            export AWS_IMAGE_NAME=$BASE_NAME-$GIT_BRANCH-$GIT_REV-$(date +%y%m%d%H%M)
            packer build ./packer.json
